search:
  paths: # Where to search for notes
    - ~/Documents/workspace/tmp
    - ~/Documents/workspace/tmp2
    - ~/Documents/workspace/tmp3
  filters: # Files to filter against
    - md
    - txt
any: false # Match any vs all topics, not yet implemented
nopause: true # Don't pause between matched topics